# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 20:58
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa: E501
                ('email', models.EmailField(max_length=254, verbose_name='Email')),  # noqa: E501
                ('name', models.CharField(max_length=64, verbose_name='Name')),  # noqa: E501
                ('issue', models.CharField(choices=[('Issue #1', 'Issue #1'), ('Issue #2', 'Issue #2'), ('Issue #3', 'Issue #3'), ('Issue #4', 'Issue #4'), ('Other', 'Other')], max_length=64, verbose_name='Issue')),  # noqa: E501
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=64, verbose_name='Severity')),  # noqa: E501
                ('description', models.TextField(verbose_name='Description')),  # noqa: E501
                ('issue_submit_date', models.DateTimeField(auto_now=True, verbose_name='Submitted date')),  # noqa: E501
                ('ticket_uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Ticket ID')),  # noqa: E501
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),  # noqa: E501
            ],
        ),
    ]
