# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issue',
            field=models.CharField(choices=[('#1', 'Issue #1'), ('#2', 'Issue #2'), ('#3', 'Issue #3'), ('#4', 'Issue #4'), ('Other', 'Other')], max_length=64, verbose_name='Issue'),  # noqa: E501
        ),
    ]
