# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 23:05
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20171029_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issue',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Issue #1'), (2, 'Issue #2'), (3, 'Issue #3'), (4, 'Issue #4')], verbose_name='Issue'),  # noqa: E501
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ticket owner'),  # noqa: E501
        ),
        migrations.AlterField(
            model_name='ticket',
            name='severity',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], verbose_name='Severity'),  # noqa: E501
        ),
    ]
