# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 23:12
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20171030_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issue',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Issue #1'), (2, 'Issue #2'), (3, 'Issue #3'), (4, 'Issue #4')], verbose_name='issue'),  # noqa: E501
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issue_submit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date submitted'),  # noqa: E501
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='severity',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], verbose_name='severity'),  # noqa: E501
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='ticket UUID'),  # noqa: E501
        ),
    ]
