# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20171030_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='severity',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Critical')], verbose_name='severity'),  # noqa: E501
        ),
    ]
