# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 10:53
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0006_ticket_has_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa: E501
                ('date', models.DateTimeField(auto_now=True, verbose_name='date')),  # noqa: E501
                ('answer', models.TextField(verbose_name='answer')),
                ('linked_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket', verbose_name='linked ticket')),  # noqa: E501
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),  # noqa: E501
            ],
        ),
    ]
