# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='linked_ticket_owner',
            field=models.CharField(default=None, max_length=64, verbose_name='ticket owner'),  # noqa: E501
        ),
    ]
