# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_reply_linked_ticket_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='linked_ticket',
            new_name='ticket',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='linked_ticket_owner',
        ),
    ]
