# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 11:17
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20171113_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket', verbose_name='ticket'),  # noqa: E501
        ),
    ]
