# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20171113_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issue',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Issue 1'), (2, 'Issue 2'), (3, 'Issue 3'), (4, 'Issue 4')], verbose_name='issue'),  # noqa: E501
        ),
    ]
